server:
  port: 8080
  servlet:
    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /Users/zhangming/log/
#  file: /Users/zhangming/log/sell.log
##  指定日志级别，默认info
#  level:
##   指定特殊类的级别
#    com.imooc.sell.LoggerTest: debug

wechat:
  mpAppId: wx2f8a32822d551206
  mpAppSecret: b75b7137c3b0345c8ac5318d9708d132
  mchId: mchIdxxxxxx
  mchKey: mchKeyxxxxxx
  mchKeyPath: /var/weichat_cert/h5.p12 #证书的下载，参考8-7 微信退款，实际支付也是需要的
  notifyUrl: http://mishi.fantreal.com/sell/pay/notify